#!/bin/bash

# Git commit-msg hooks. https://github.com/cavo789/bash_git_hooks/
#
# Please read https://github.com/cavo789/bash_git_hooks#install for installation guide
#
# This script will fires, one by one and in an alphabetical order, each bash
# scripts present in the commit-msg-scripts sub-folder. As soon as one of these
# scripts returns an exitcode different than 0, the git commit action will be aborted
# and an error message will be displayed

# Remember the first parameter: the name of the file where the commit message is saved
COMMIT_MSG="$1"

# http://patorjk.com/software/taag/#p=display&f=Big&t=commit-msg
cat <<\EOF
                                _ _                              
                               (_) |                             
   ___ ___  _ __ ___  _ __ ___  _| |_ ______ _ __ ___  ___  __ _ 
  / __/ _ \| '_ ` _ \| '_ ` _ \| | __|______| '_ ` _ \/ __|/ _` |
 | (_| (_) | | | | | | | | | | | | |_       | | | | | \__ \ (_| |
  \___\___/|_| |_| |_|_| |_| |_|_|\__|      |_| |_| |_|___/\__, |
                                                            __/ |
                                                           |___/ 

EOF

printf "\e[1;33m%s\e[m\n" "Tips:" >&1
printf "\e[1;33m%s\e[m\n" "  1. run .git/hooks/commit-msg on the command line to start, anytime, these checks." >&1
printf "\e[1;33m%s\e[m\n\n" "  2. To disable a check, just rename it by adding an underscore as the first character of his filename." >&1

HOOK_FOLDER="commit-msg-scripts"

# Get the alphabetical list of commit-msg hooks and run them one by one.
# As soon as one hook failed, the commit-msg hook will fails and the commit
# action will be aborted.

# Folder containing this script
CURDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Loop
# shellcheck disable=SC2012
for FILE in $(ls "$CURDIR/$HOOK_FOLDER/" | sort -g); do

    # Extract the first character of the filename
    short="${FILE:0:1}"

    # Get full path
    FILE=$(realpath "$CURDIR/$HOOK_FOLDER/$FILE")

    # Skip scripts when the name starts with an underscore
    if [[ ! "$short" == "_" ]]; then

        printf "\e[1;30m%s\e[m\n" "Process $FILE" >&1

        # Run and capture the output of the script (both normal output and errors)
        OUTPUT=$(/bin/bash "$FILE" "$COMMIT_MSG")
        exitCode=$?

        if [[ -n $OUTPUT ]]; then
            printf "\n\e[1;91m%s\e[m\n" "$OUTPUT"
        fi

        if [[ "$exitCode" -gt 0 ]]; then
            # Don't execute the next hook if this one has failed
            printf "\n\e[1;91m%s\e[m\n" "ERROR! The $FILE has failed with the following error:" >&2
            printf "\n\e[1;91m%s\e[m\n" "The current git action is aborted." >&2
            exit 1
        fi
    else
        printf "\e[0;100m%s\e[m\n" "Skip    $FILE" >&1
    fi
done

printf "\n\e[1;92m%s\e[m\n" "${BASH_SOURCE[0]} Success!"
